version: '3.8' # Docker Compose 파일 버전

services:
  redis:
    image: redis:7.2.3-alpine # Redis 이미지 및 버전
    container_name: redis-container # Redis 컨테이너 이름
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - spring-network # Redis 컨테이너가 연결될 네트워크

networks:
  spring-network:
    driver: bridge # 기본 브리지 네트워크 드라이버를 사용합니다.
